"""updated the user class and added the bio and profile

Revision ID: 50302ddc57f9
Revises: 692f4b542e27
Create Date: 2022-05-11 15:38:18.634075

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50302ddc57f9'
down_revision = '692f4b542e27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('bio', sa.String(length=400), nullable=True))
    op.add_column('users', sa.Column('profile_pic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_pic')
    op.drop_column('users', 'bio')
    # ### end Alembic commands ###
