"""updated the user class

Revision ID: 692f4b542e27
Revises: 156cdd56581e
Create Date: 2022-05-11 14:33:05.919224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '692f4b542e27'
down_revision = '156cdd56581e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=300), nullable=True))
    op.add_column('users', sa.Column('pass_s', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'pass_s')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
